apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p6vmqljpr-go 
  janus-idp.io/tekton: p6vmqljpr-go
  backstage.io/kubernetes-id: p6vmqljpr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p6vmqljpr-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml