apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: p6vmqljpr-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9a325191bf.4e4l.p3.openshiftapps.com/rhtap/rhtap-qe-go:08cfbd9c64bd58b5018f521814b2671f602f1fcc@sha256:97a167ecb4d1b7b0cad4a1aeaaed9b018064801088a2d592361aa28c51caf2ec
          name: container-image
